import SwiftUI

struct ZeusPrehistoryModel {
    let arrayOfText = ["I, ZEUS, THE SUPREME GOD OF OLYMPUS, THE THUNDERER AND LORD OF THE SKIES, HAVE NOTICED THAT OUR SACRED OLYMPUS HAS LONG BEEN DEVOID OF FESTIVITIES, AND THE GODS AND MORTALS HAVE CEASED TO INTERACT. THIS CANNOT CONTINUE, FOR UNITY AND HARMONY BETWEEN US ARE THE FOUNDATION OF OUR EXISTENCE.",
                       "I HAVE DECIDED TO CHANGE THIS STATE OF AFFAIRS AND RESTORE THE BOND BETWEEN GODS, HUMANS, AND NATURE. TO ACHIEVE THIS, I WILL ARRANGE GREAT TRIALS THAT WILL UNITE US ALL AND BRING BACK THE FORMER GLORY TO OUR RELATIONSHIPS. LET THESE TRIALS BE A SYMBOL OF OUR UNITY AND STRENGTH.",
                       "HEAR MY WORDS, FOR THEY ARE FILLED WITH WISDOM AND POWER. MAY EACH OF YOU, GODS AND MORTALS ALIKE, PARTICIPATE IN THESE TRIALS WITH AN OPEN HEART AND PURE INTENTIONS. SO LET IT BE!"]
}


